### ISSUE TITLE
add Amsterdam to the site

### ISSUE THREAD

**Issue by ksatirli** [WebPerfDays/WebPerfDays.org#5]
Hey folks,

I just noticed there's a branch for the 2016 edition in Amsterdam: https://github.com/WebPerfDays/WebPerfDays.org/tree/master/events/2016-amsterdam

Any chance we could get that added to the site? 

Happy to make a PR, but I'm not the original author, so it feels strange doing that.

CC: @measureworks

**Comment by 1ngr1d** [comment]
Hi WebPerfDays/WebPerfDays.org,  Feel free to update the webperfdays.org website :-) Thanks!  
  
 Mvg Bas van der Toorn  
 
 
 
                 
         Op Di, 1 Nov at 10:26 AM
          ,  WebPerfDays/WebPerfDays.org <reply@reply.github.com>  schreef:
           Hey folks, 
 I just noticed there's a branch for the 2016 edition in Amsterdam: https://github.com/WebPerfDays/WebPerfDays.org/tree/master/events/2016-amsterdam
 
 Any chance we could get that added to the site? 
 Happy to make a PR, but I'm not the original author, so it feels strange doing that. 
 CC: @measureworks

**Comment by sergeychernyshev** [comment]
@AaronKulick, it might be a good idea to finally switch domain to GitHub pages so we don't block event organizers around the globe from posting their events.
